/** **********************************************************************
    * This file is auto-generated by nxsdk_remote_stub_gen.py 
    * at 2018-09-26 21:31:54.742936
    * 
    * Copyright (c) 2017 by cisco Systems, Inc.
    *
    * All rights reserved.
************************************************************************/
#ifndef __nx_adj_mgr_impl_H__
#define __nx_adj_mgr_impl_H__

#include "nx_adj_mgr.h" 
   
using namespace nxos;

   
namespace nxos {

class NxAdjImpl : public NxAdj {
public:
    NxAdjImpl();
    virtual ~NxAdjImpl();
    std::string getIpAddr();
    std::string getMacAddr();
    std::string getVrf();
    std::string getIntfName();
    std::string getPhyIntfName();
    unsigned int getPreference();
    std::string getSource();
    nxos::event_type_e getEvent();
    nxos::af_e getAF();
    bool operator==(NxAdj const &adj_obj) const;
    bool operator!=(NxAdj const &adj_obj) const;
    bool equal(NxAdj const &adj_obj) const;
};

class NxAdjMgrImpl : public NxAdjMgr {
public:
    NxAdjMgrImpl();
    virtual ~NxAdjMgrImpl();
    NxAdj* getAdj(const std::string &intfName,const std::string &ipAddr);
    bool discoverAdj(const std::string &intfName,const std::string &ipAddr);
    void watchAllAdjs(nxos::af_e addr_family = AF_IPV4,bool download = true);
    void unwatchAllAdjs(nxos::af_e addr_family = AF_IPV4);
    bool watchAdj(const std::string &intfName,nxos::af_e addr_family = AF_IPV4,bool download = true,const std::string &ipAddr = "");
    bool unwatchAdj(const std::string &intfName,nxos::af_e addr_family = AF_IPV4,const std::string &ipAddr = "");
    void setAdjMgrHandler(NxAdjMgrHandler *handler);
    void unsetAdjMgrHandler();
    NxAdjMgrHandler* getAdjMgrHandler();
};
}
#endif // __nx_adj_mgr_impl_H__ 