/** **********************************************************************
    * This file is auto-generated by nxsdk_remote_stub_gen.py 
    * at 2019-07-18 23:18:33.479867
    * 
    * Copyright (c) 2017 by cisco Systems, Inc.
    *
    * All rights reserved.
************************************************************************/
#include "nx_adj_mgr_impl.h" 
   
using namespace nxos;

   
    
// Implementation for class  
NxAdjImpl::NxAdjImpl()
{

}

NxAdjImpl::~NxAdjImpl()
{

}

std::string 
NxAdjImpl::getIpAddr()
{
   return "";
}

std::string 
NxAdjImpl::getMacAddr()
{
   return "";
}

std::string 
NxAdjImpl::getVrf()
{
   return "";
}

std::string 
NxAdjImpl::getIntfName()
{
   return "";
}

std::string 
NxAdjImpl::getPhyIntfName()
{
   return "";
}

unsigned int 
NxAdjImpl::getPreference()
{
   return (unsigned int)0;
}

std::string 
NxAdjImpl::getSource()
{
   return "";
}

nxos::event_type_e 
NxAdjImpl::getEvent()
{
   return (nxos::event_type_e)0;
}

nxos::af_e 
NxAdjImpl::getAF()
{
   return (nxos::af_e)0;
}

bool 
NxAdjImpl::operator==(NxAdj const& adj_obj) const
{
   return false;
}

bool 
NxAdjImpl::operator!=(NxAdj const& adj_obj) const
{
   return false;
}

bool 
NxAdjImpl::equal(NxAdj const& adj_obj) const
{
   return false;
}
    
// Implementation for class  
NxAdjMgrImpl::NxAdjMgrImpl()
{

}

NxAdjMgrImpl::~NxAdjMgrImpl()
{

}

NxAdj* 
NxAdjMgrImpl::getAdj(const std::string& intfName, const std::string& ipAddr)
{
   return NULL;
}

bool 
NxAdjMgrImpl::discoverAdj(const std::string& intfName, const std::string& ipAddr)
{
   return false;
}

void 
NxAdjMgrImpl::watchAllAdjs(nxos::af_e addr_family, bool download)
{
   return;
}

void 
NxAdjMgrImpl::unwatchAllAdjs(nxos::af_e addr_family)
{
   return;
}

bool 
NxAdjMgrImpl::watchAdj(const std::string& intfName, nxos::af_e addr_family, bool download, const std::string& ipAddr)
{
   return false;
}

bool 
NxAdjMgrImpl::unwatchAdj(const std::string& intfName, nxos::af_e addr_family, const std::string& ipAddr)
{
   return false;
}

void 
NxAdjMgrImpl::setAdjMgrHandler(NxAdjMgrHandler* handler)
{
   return;
}

void 
NxAdjMgrImpl::unsetAdjMgrHandler()
{
   return;
}

NxAdjMgrHandler* 
NxAdjMgrImpl::getAdjMgrHandler()
{
   return NULL;
}