/** **********************************************************************
    * This file is auto-generated by nxsdk_remote_stub_gen.py 
    * at 2019-10-31 05:25:27.235484
    * 
    * Copyright (c) 2017 by cisco Systems, Inc.
    *
    * All rights reserved.
************************************************************************/
#ifndef __nx_exception_impl_H__
#define __nx_exception_impl_H__

#include "nx_exception.h" 
   
using namespace nxos;

   
namespace nxos {

class NxExceptionImpl : public NxException {
public:
    NxExceptionImpl();
    virtual ~NxExceptionImpl();
    const char * what();
    unsigned long getErrCode();
    const char * getErrModule();
    unsigned short getErrSeverity();
    const char * getErrApi();
};
}
#endif // __nx_exception_impl_H__ 