/** **********************************************************************
    * This file is auto-generated by nxsdk_remote_stub_gen.py 
    * at 2019-10-31 05:25:27.235820
    * 
    * Copyright (c) 2017 by cisco Systems, Inc.
    *
    * All rights reserved.
************************************************************************/
#include "nx_exception_impl.h" 
   
using namespace nxos;

   
    
// Implementation for class  
NxExceptionImpl::NxExceptionImpl()
{

}

NxExceptionImpl::~NxExceptionImpl()
{

}

const char * 
NxExceptionImpl::what()
{
   return NULL;
}

unsigned long 
NxExceptionImpl::getErrCode()
{
   return (unsigned long)0;
}

const char * 
NxExceptionImpl::getErrModule()
{
   return NULL;
}

unsigned short 
NxExceptionImpl::getErrSeverity()
{
   return (unsigned short)0;
}

const char * 
NxExceptionImpl::getErrApi()
{
   return NULL;
}