/** **********************************************************************
    * This file is auto-generated by nxsdk_remote_stub_gen.py 
    * at 2019-10-31 05:25:27.247337
    * 
    * Copyright (c) 2017 by cisco Systems, Inc.
    *
    * All rights reserved.
************************************************************************/
#ifndef __nx_sdk_impl_H__
#define __nx_sdk_impl_H__

#include "nx_sdk.h" 
   
using namespace nxos;

   
namespace nxos {

class NxSdkImpl : public NxSdk {
public:
    NxSdkImpl();
    virtual ~NxSdkImpl();
    void setAppDesc(std::string desc);
    const char* getAppName();
    const char* getAppDesc();
    int getAppId();
    NxCliParser* getCliParser();
    NxTrace* getTracer();
    void startEventLoop();
    void stopEventLoop();
    NxRibMgr* getRibMgr();
    void setAppPriority(nxos::prio_e prio);
    NxIntfMgr* getIntfMgr();
    NxAdjMgr* getAdjMgr();
    NxMacMgr* getMacMgr();
    NxDmeMgr* getDmeMgr();
    bool isInEventLoop() const;
    nxos::running_env_e getRunningEnv() const;
    std::string getRemoteIp();
    uint32_t getRemotePort();
    nxos::state_type_e getRemoteConnStatus();
    void purgeAllSdkObjs();
    void setSdkHandler(NxSdkHandler *handler);
    void unsetSdkHandler();
    NxSdkHandler* getSdkHandler();
    std::string getNxSdkVersion();
    std::string getRemoteClientNxSdkVersion();
};
}
#endif // __nx_sdk_impl_H__ 