/** **********************************************************************
    * This file is auto-generated by nxsdk_remote_stub_gen.py 
    * at 2018-09-26 21:31:54.742030
    * 
    * Copyright (c) 2017 by cisco Systems, Inc.
    *
    * All rights reserved.
************************************************************************/
#include "nx_sdk_impl.h" 
   
using namespace nxos;

   
    
// Implementation for class  
NxSdkImpl::NxSdkImpl()
{

}

NxSdkImpl::~NxSdkImpl()
{

}

NxSdk* 
NxSdk::getSdkInst(int argc, char** argv)
{
   return NULL;
}

void 
NxSdkImpl::setAppDesc(std::string desc)
{
   return;
}

const char* 
NxSdkImpl::getAppName()
{
   return NULL;
}

const char* 
NxSdkImpl::getAppDesc()
{
   return NULL;
}

int 
NxSdkImpl::getAppId()
{
   return (int)0;
}

NxCliParser* 
NxSdkImpl::getCliParser()
{
   return NULL;
}

NxTrace* 
NxSdkImpl::getTracer()
{
   return NULL;
}

void 
NxSdkImpl::startEventLoop()
{
   return;
}

void 
NxSdkImpl::stopEventLoop()
{
   return;
}

NxSdk* 
NxSdk::getSdkInst(int argc, char** argv, bool advException)
{
   return NULL;
}

NxRibMgr* 
NxSdkImpl::getRibMgr()
{
   return NULL;
}

void 
NxSdkImpl::setAppPriority(nxos::prio_e prio)
{
   return;
}

NxIntfMgr* 
NxSdkImpl::getIntfMgr()
{
   return NULL;
}

NxAdjMgr* 
NxSdkImpl::getAdjMgr()
{
   return NULL;
}

NxMacMgr* 
NxSdkImpl::getMacMgr()
{
   return NULL;
}

NxDmeMgr* 
NxSdkImpl::getDmeMgr()
{
   return NULL;
}

bool 
NxSdkImpl::isInEventLoop() const
{
   return false;
}

nxos::running_env_e 
NxSdkImpl::getRunningEnv() const
{
   return (nxos::running_env_e)0;
}