/** **********************************************************************
    * This file is auto-generated by nxsdk_remote_stub_gen.py 
    * at 2019-07-18 23:18:33.471688
    * 
    * Copyright (c) 2017 by cisco Systems, Inc.
    *
    * All rights reserved.
************************************************************************/
#include "nx_trace_impl.h" 
   
using namespace nxos;

   
    
// Implementation for class  
NxTraceImpl::NxTraceImpl()
{

}

NxTraceImpl::~NxTraceImpl()
{

}

void 
NxTraceImpl::syslog(Priority prio, const char* fmt,  ...)
{
   return;
}

void 
NxTraceImpl::event(const char* fmt,  ...)
{
   return;
}

void 
NxTraceImpl::error(const char* fmt,  ...)
{
   return;
}

const char* 
NxTrace::getPrioStr(Priority prio)
{
   return NULL;
}