/** **********************************************************************
    * This file is auto-generated by nxsdk_remote_stub_gen.py 
    * at 2019-10-31 05:25:27.238916
    * 
    * Copyright (c) 2017 by cisco Systems, Inc.
    *
    * All rights reserved.
************************************************************************/
#include "nx_trace_impl.h" 
   
using namespace nxos;

   
    
// Implementation for class  
NxSyslogImpl::NxSyslogImpl()
{

}

NxSyslogImpl::~NxSyslogImpl()
{

}

uint32_t 
NxSyslogImpl::getId()
{
   return (uint32_t)0;
}

std::string 
NxSyslogImpl::getNodeName()
{
   return "";
}

std::string 
NxSyslogImpl::getTimeStamp()
{
   return "";
}

uint32_t 
NxSyslogImpl::getSeverity()
{
   return (uint32_t)0;
}

std::string 
NxSyslogImpl::getMessageName()
{
   return "";
}

std::string 
NxSyslogImpl::getCategory()
{
   return "";
}

std::string 
NxSyslogImpl::getText()
{
   return "";
}

std::string 
NxSyslogImpl::getTimeZone()
{
   return "";
}
    
// Implementation for class  
NxTraceImpl::NxTraceImpl()
{

}

NxTraceImpl::~NxTraceImpl()
{

}

void 
NxTraceImpl::syslog(Priority prio, const char* fmt,  ...)
{
   return;
}

void 
NxTraceImpl::event(const char* fmt,  ...)
{
   return;
}

void 
NxTraceImpl::error(const char* fmt,  ...)
{
   return;
}

const char* 
NxTrace::getPrioStr(Priority prio)
{
   return NULL;
}

bool 
NxTraceImpl::watchSyslog(bool download)
{
   return false;
}

void 
NxTraceImpl::unwatchSyslog()
{
   return;
}

void 
NxTraceImpl::setTraceHandler(NxTraceHandler* handler)
{
   return;
}

NxTraceHandler* 
NxTraceImpl::getTraceHandler()
{
   return NULL;
}