/** **********************************************************************
    * This file is auto-generated by nxsdk_remote_stub_gen.py 
    * at 2019-07-18 23:18:33.471178
    * 
    * Copyright (c) 2017 by cisco Systems, Inc.
    *
    * All rights reserved.
************************************************************************/
#ifndef __nx_trace_impl_H__
#define __nx_trace_impl_H__

#include "nx_trace.h" 
   
using namespace nxos;

   
namespace nxos {

class NxTraceImpl : public NxTrace {
public:
    NxTraceImpl();
    virtual ~NxTraceImpl();
    void syslog(Priority prio, const char *fmt, ...);
    void event(const char *fmt, ...);
    void error(const char *fmt, ...);
};
}
#endif // __nx_trace_impl_H__ 