/** **********************************************************************
    * This file is auto-generated by nxsdk_remote_stub_gen.py 
    * at 2019-10-31 05:25:27.237882
    * 
    * Copyright (c) 2017 by cisco Systems, Inc.
    *
    * All rights reserved.
************************************************************************/
#ifndef __nx_trace_impl_H__
#define __nx_trace_impl_H__

#include "nx_trace.h" 
   
using namespace nxos;

   
namespace nxos {

class NxSyslogImpl : public NxSyslog {
public:
    NxSyslogImpl();
    virtual ~NxSyslogImpl();
    uint32_t getId();
    std::string getNodeName();
    std::string getTimeStamp();
    uint32_t getSeverity();
    std::string getMessageName();
    std::string getCategory();
    std::string getText();
    std::string getTimeZone();
};

class NxTraceImpl : public NxTrace {
public:
    NxTraceImpl();
    virtual ~NxTraceImpl();
    void syslog(Priority prio, const char *fmt, ...);
    void event(const char *fmt, ...);
    void error(const char *fmt, ...);
    bool watchSyslog(bool download = true);
    void unwatchSyslog();
    void setTraceHandler(NxTraceHandler *handler);
    NxTraceHandler* getTraceHandler();
};
}
#endif // __nx_trace_impl_H__ 